# Generated by Django 6.0 on 2026-01-02 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Grade value obtained by student', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('max_value', models.DecimalField(decimal_places=2, help_text='Maximum possible grade value', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max value')),
                ('type', models.CharField(choices=[('exam', 'Examen'), ('assignment', 'Devoir'), ('project', 'Projet'), ('participation', 'Participation')], db_index=True, max_length=20, verbose_name='type')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='sessions.session', verbose_name='session')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'db_table': 'grades',
                'ordering': ['-date', 'student'],
            },
        ),
    ]
