# Generated by Django 6.0 on 2026-01-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('programs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='programs.subject', verbose_name='subject'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject'], name='grades_student_f99f41_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'session'], name='grades_student_d82a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject', 'session'], name='grades_subject_a610b3_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['-date'], name='grades_date_6ca239_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['type'], name='grades_type_aa7fa1_idx'),
        ),
    ]
