# Generated by Django 6.0 on 2026-01-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic_sessions.session', verbose_name='session'),
        ),
    ]
