# Generated by Django 6.0 on 2026-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'Retard'), ('excused', 'Absence justifiée')], db_index=True, default='present', max_length=20, verbose_name='status')),
                ('justification', models.TextField(blank=True, help_text='Justification for absence or lateness', null=True, verbose_name='justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'db_table': 'attendances',
                'ordering': ['-date', 'student'],
            },
        ),
    ]
