# Generated by Django 6.0 on 2026-01-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('programs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='programs.subject', verbose_name='subject'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendances_student_1e9785_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'date'], name='attendances_subject_b0075b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'date'], name='attendances_status_dcc3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['-date'], name='attendances_date_40b64d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
