"""
Create initial data migrations for SPAS.

This script generates data migrations for:
- User roles and permissions
- Grade types
- Alert types and levels
- Session types
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Add the project root to the path
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

# Migration templates

USERS_INITIAL_DATA = """# Generated by create_initial_data_migrations.py

from django.db import migrations


def create_initial_groups_and_permissions(apps, schema_editor):
    \"\"\"Create initial user groups with appropriate permissions.\"\"\"
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Define permission sets for each role
    role_permissions = {
        'Administrateur': [
            'can_view_analytics',
            'can_manage_students',
            'can_manage_programs',
            'can_manage_grades',
            'can_manage_attendance',
            'can_run_ml_predictions',
            'can_view_predictions',
            'can_manage_alerts',
        ],
        'Directeur des Études': [
            'can_view_analytics',
            'can_manage_students',
            'can_manage_programs',
            'can_manage_grades',
            'can_manage_attendance',
            'can_view_predictions',
            'can_manage_alerts',
        ],
        'Conseiller Pédagogique': [
            'can_view_analytics',
            'can_manage_students',
            'can_view_predictions',
            'can_manage_alerts',
        ],
        'Enseignant': [
            'can_manage_grades',
            'can_manage_attendance',
            'can_view_predictions',
        ],
    }

    # Create groups and assign permissions
    for role_name, permission_codes in role_permissions.items():
        group, created = Group.objects.get_or_create(name=role_name)
        if created:
            print(f"Created group: {role_name}")

        # Get User content type
        try:
            user_ct = ContentType.objects.get(app_label='users', model='user')
            for perm_code in permission_codes:
                try:
                    permission = Permission.objects.get(
                        codename=perm_code,
                        content_type=user_ct
                    )
                    group.permissions.add(permission)
                except Permission.DoesNotExist:
                    print(f"Warning: Permission {perm_code} not found")
        except ContentType.DoesNotExist:
            print("Warning: User content type not found")


def reverse_initial_groups(apps, schema_editor):
    \"\"\"Remove initial groups.\"\"\"
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            'Administrateur',
            'Directeur des Études',
            'Conseiller Pédagogique',
            'Enseignant'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_groups_and_permissions,
            reverse_initial_groups
        ),
    ]
"""

ALERTS_INITIAL_DATA = """# Generated by create_initial_data_migrations.py

from django.db import migrations


def create_alert_type_choices(apps, schema_editor):
    \"\"\"Create documentation for alert type choices.\"\"\"
    # Alert types are defined as TextChoices in the model
    # This migration serves as documentation that initial alert types are:
    # - PERFORMANCE: For academic performance issues
    # - ATTENDANCE: For attendance problems
    # - RISK: For at-risk students
    # - PREDICTION: For ML prediction-based alerts
    pass


def reverse_alert_types(apps, schema_editor):
    \"\"\"Reverse migration - no-op since alert types are model-defined.\"\"\"
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_alert_type_choices,
            reverse_alert_types
        ),
    ]
"""


def create_data_migration(app_name, migration_content):
    """Create a data migration file for the specified app."""
    migrations_dir = BASE_DIR / 'apps' / app_name / 'migrations'
    migrations_dir.mkdir(exist_ok=True)

    # Ensure __init__.py exists
    init_file = migrations_dir / '__init__.py'
    if not init_file.exists():
        init_file.write_text('')

    # Find next migration number
    existing_migrations = list(migrations_dir.glob('[0-9]*.py'))
    if existing_migrations:
        numbers = [int(m.stem.split('_')[0]) for m in existing_migrations]
        next_number = max(numbers) + 1
    else:
        next_number = 2  # Assuming 0001_initial exists

    # Create migration file
    migration_file = migrations_dir / f'{next_number:04d}_initial_data.py'

    if migration_file.exists():
        print(f"Migration already exists: {migration_file}")
        return False

    migration_file.write_text(migration_content)
    print(f"Created migration: {migration_file}")
    return True


def main():
    """Create all initial data migrations."""
    print("=" * 60)
    print("Creating Initial Data Migrations for SPAS")
    print("=" * 60)
    print()

    migrations_to_create = [
        ('users', USERS_INITIAL_DATA),
        ('alerts', ALERTS_INITIAL_DATA),
    ]

    created_count = 0
    for app_name, content in migrations_to_create:
        if create_data_migration(app_name, content):
            created_count += 1

    print()
    print("=" * 60)
    print(f"Created {created_count} data migration(s)")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Review the created migrations")
    print("  2. Run: python manage.py migrate")
    print()


if __name__ == '__main__':
    main()
