# Generated by Django 6.0 on 2026-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('performance', 'Performance'), ('attendance', 'Présence'), ('risk', 'Risque'), ('prediction', 'Prédiction')], db_index=True, max_length=20, verbose_name='type')),
                ('level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], db_index=True, max_length=20, verbose_name='level')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('acknowledged', 'Accusé réception'), ('resolved', 'Résolu')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
