# Generated by Django 6.0 on 2026-01-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='students.student', verbose_name='student'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['student', 'status'], name='alerts_student_2da014_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type', 'level'], name='alerts_type_16103c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_status_5c7524_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='alerts_created_6327ec_idx'),
        ),
    ]
