# Generated by Django 6.0 on 2026-01-02 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('students', '0002_fix_session_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meeting', 'Entretien individuel'), ('tutoring', 'Tutorat'), ('alert', 'Alerte précoce'), ('email', 'Email de suivi'), ('phone', 'Appel téléphonique'), ('parent_contact', 'Contact parents'), ('academic_support', 'Soutien académique'), ('other', 'Autre')], db_index=True, max_length=20, verbose_name='type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='planned', max_length=20, verbose_name='status')),
                ('description', models.TextField(verbose_name='description')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='completed date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('outcome', models.TextField(blank=True, verbose_name='outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='alerts.alert', verbose_name='related alert')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL, verbose_name='responsible')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
                'db_table': 'interventions',
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='interventio_student_10b4a1_idx'), models.Index(fields=['type', 'priority'], name='interventio_type_503868_idx'), models.Index(fields=['scheduled_date'], name='interventio_schedul_69475a_idx'), models.Index(fields=['responsible', 'status'], name='interventio_respons_695c4a_idx')],
            },
        ),
    ]
