# Generated by Django 6.0 on 2026-01-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
