# Generated by Django 6.0 on 2026-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('year', models.CharField(help_text='Academic year (e.g., 2023-2024)', max_length=20, verbose_name='year')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('completed', 'Terminé')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'sessions',
                'ordering': ['-year', '-start_date'],
                'indexes': [models.Index(fields=['year'], name='sessions_year_9079f7_idx'), models.Index(fields=['status'], name='sessions_status_2c94db_idx'), models.Index(fields=['-start_date'], name='sessions_start_d_002b39_idx')],
                'unique_together': {('name', 'year')},
            },
        ),
    ]
