# Generated by Django 6.0 on 2026-01-03 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_auto_training', models.BooleanField(default=True, help_text='Enable automatic ML model retraining')),
                ('ml_training_frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', help_text='Frequency of automatic training', max_length=20)),
                ('ml_risk_threshold_low', models.FloatField(default=0.3, help_text='Threshold for low risk (0-1)')),
                ('ml_risk_threshold_medium', models.FloatField(default=0.6, help_text='Threshold for medium risk (0-1)')),
                ('ml_risk_threshold_high', models.FloatField(default=0.8, help_text='Threshold for high risk (0-1)')),
                ('alert_auto_create', models.BooleanField(default=True, help_text='Automatically create alerts for high-risk students')),
                ('alert_email_notifications', models.BooleanField(default=True, help_text='Send email notifications for new alerts')),
                ('alert_sms_notifications', models.BooleanField(default=False, help_text='Send SMS notifications for critical alerts')),
                ('notification_email_enabled', models.BooleanField(default=True)),
                ('notification_sms_enabled', models.BooleanField(default=False)),
                ('notification_push_enabled', models.BooleanField(default=True)),
                ('academic_year_start_month', models.IntegerField(default=9, help_text='Month when academic year starts (1-12)')),
                ('academic_passing_grade', models.FloatField(default=10.0, help_text='Minimum passing grade (0-20)')),
                ('academic_attendance_threshold', models.FloatField(default=75.0, help_text='Minimum attendance percentage required')),
                ('system_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10)),
                ('system_timezone', models.CharField(default='Africa/Dakar', max_length=50)),
                ('system_date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('system_maintenance_mode', models.BooleanField(default=False)),
                ('data_retention_years', models.IntegerField(default=7, help_text='Number of years to retain student data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Exportation'), ('import', 'Importation'), ('ml_prediction', 'Prédiction ML'), ('alert_created', 'Alerte créée'), ('alert_resolved', 'Alerte résolue'), ('permission_denied', 'Permission refusée'), ('error', 'Erreur')], db_index=True, help_text="Le type d'action effectuée", max_length=50, verbose_name='action')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="ID de l'objet")),
                ('model_name', models.CharField(db_index=True, help_text='Le nom du modèle affecté', max_length=100, verbose_name='nom du modèle')),
                ('object_repr', models.CharField(blank=True, help_text="Représentation textuelle de l'objet au moment de l'action", max_length=200, verbose_name="représentation de l'objet")),
                ('changes', models.JSONField(blank=True, help_text='Détails des changements effectués (format JSON)', null=True, verbose_name='changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="L'adresse IP de l'utilisateur", null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, help_text='Le user agent du navigateur', max_length=500, verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Quand l'action a été effectuée", verbose_name='horodatage')),
                ('endpoint', models.CharField(blank=True, help_text="L'endpoint API appelé", max_length=200, verbose_name='endpoint')),
                ('method', models.CharField(blank=True, help_text='La méthode HTTP utilisée (GET, POST, etc.)', max_length=10, verbose_name='méthode HTTP')),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='Le code de statut HTTP de la réponse', null=True, verbose_name='code de statut')),
                ('extra_data', models.JSONField(blank=True, help_text='Informations supplémentaires (format JSON)', null=True, verbose_name='données supplémentaires')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type de contenu')),
                ('user', models.ForeignKey(blank=True, help_text="L'utilisateur qui a effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['model_name', 'timestamp'], name='audit_logs_model_n_764981_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_logs_ip_addr_932507_idx')],
            },
        ),
    ]
