# Generated by Django 5.0.14 on 2026-07-18 19:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Détails des changements effectués (format JSON)",
                null=True,
                verbose_name="changements",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Informations supplémentaires (format JSON)",
                null=True,
                verbose_name="données supplémentaires",
            ),
        ),
    ]
