# Generated by Django 6.0 on 2026-01-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(db_index=True, help_text='Unique program code', max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('duration', models.IntegerField(help_text='Program duration in years', validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration (years)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'db_table': 'programs',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='programs_code_a0c867_idx'), models.Index(fields=['status'], name='programs_status_1f33ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(db_index=True, help_text='Unique subject code', max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('programs', models.ManyToManyField(help_text='Programs that include this subject', related_name='subjects', to='programs.program', verbose_name='programs')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'subjects',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='subjects_code_3f80fa_idx')],
            },
        ),
    ]
