# Generated by Django 6.0 on 2026-01-03 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Department name (e.g., "Département Réseaux et Systèmes")', max_length=200, unique=True, verbose_name='name')),
                ('code', models.CharField(db_index=True, help_text='Unique department code (e.g., "DRS", "DGI")', max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'departments',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['status'], name='departments_status_e50229_idx')],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Academic department this program belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.department', verbose_name='department'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['department'], name='programs_departm_02b6f7_idx'),
        ),
    ]
