# Generated by Django 6.0 on 2026-01-02 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, help_text='Unique student identification number', max_length=50, unique=True, verbose_name='matricule')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('graduated', 'Diplômé')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], db_index=True, help_text='Predicted risk level for student success', max_length=20, null=True, verbose_name='risk level')),
                ('risk_score', models.IntegerField(blank=True, help_text='Risk score between 0-100 (higher = more at risk)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='risk score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('program', models.ForeignKey(help_text='Academic program the student is enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.program', verbose_name='program')),
                ('session', models.ForeignKey(help_text='Academic session the student is enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='sessions.session', verbose_name='session')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['matricule'], name='students_matricu_ead3a4_idx'), models.Index(fields=['email'], name='students_email_b942ac_idx'), models.Index(fields=['status'], name='students_status_3ac771_idx'), models.Index(fields=['risk_level'], name='students_risk_le_90eb0c_idx'), models.Index(fields=['program', 'session'], name='students_program_71da5b_idx')],
            },
        ),
    ]
