# Generated by Django 6.0 on 2026-01-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(help_text='Academic session the student is enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic_sessions.session', verbose_name='session'),
        ),
    ]
