# Generated by Django 6.0 on 2026-01-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_fix_session_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], db_index=True, default='L1', help_text='Academic level (L1, L2, L3, M1, M2)', max_length=5, verbose_name='level'),
        ),
    ]
