# Generated by Django 6.0 on 2026-01-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_level_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='student_photos/', verbose_name='photo'),
        ),
    ]
