# Generated by Django 5.0.14 on 2026-07-18 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_sessions", "0001_initial"),
        ("programs", "0002_department_program_department_and_more"),
        ("students", "0004_student_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher assigned to this student for read/write access scoping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="teacher",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Faible"),
                    ("medium", "Moyen"),
                    ("high", "Élevé"),
                    ("critical", "Critique"),
                ],
                db_index=True,
                help_text="Predicted risk level for student success",
                max_length=20,
                null=True,
                verbose_name="risk level",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["teacher"], name="students_teacher_5e8fea_idx"),
        ),
    ]
