# Generated by Django 6.0 on 2026-01-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('version', models.CharField(db_index=True, max_length=50, verbose_name='version')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('training', 'En Formation')], db_index=True, default='inactive', max_length=20, verbose_name='status')),
                ('accuracy', models.DecimalField(decimal_places=2, help_text='Model accuracy (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='accuracy')),
                ('precision', models.DecimalField(decimal_places=2, help_text='Model precision (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='precision')),
                ('recall', models.DecimalField(decimal_places=2, help_text='Model recall (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='recall')),
                ('f1_score', models.DecimalField(decimal_places=2, help_text='Model F1 score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='F1 score')),
                ('trained_at', models.DateTimeField(verbose_name='trained at')),
                ('training_data_size', models.IntegerField(help_text='Number of samples used for training', validators=[django.core.validators.MinValueValidator(0)], verbose_name='training data size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'ML model',
                'verbose_name_plural': 'ML models',
                'db_table': 'ml_models',
                'ordering': ['-trained_at', '-created_at'],
                'indexes': [models.Index(fields=['version'], name='ml_models_version_ad88fc_idx'), models.Index(fields=['status'], name='ml_models_status_979742_idx'), models.Index(fields=['-trained_at'], name='ml_models_trained_7bd88b_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
