# Generated by Django 6.0 on 2026-01-02 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('job_type', models.CharField(choices=[('train', 'Entraînement'), ('retrain', 'Ré-entraînement'), ('fine_tune', 'Ajustement fin')], default='train', max_length=20, verbose_name='job type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('algorithm', models.CharField(default='random_forest', help_text='ML algorithm: random_forest, gradient_boosting, logistic_regression', max_length=50, verbose_name='algorithm')),
                ('hyperparameters', models.JSONField(blank=True, default=dict, help_text='JSON object with hyperparameters', verbose_name='hyperparameters')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature names to use', verbose_name='features')),
                ('progress', models.IntegerField(default=0, help_text='Training progress (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress')),
                ('current_step', models.CharField(blank=True, max_length=100, null=True, verbose_name='current step')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='logs')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('resulting_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='ml.mlmodel', verbose_name='resulting model')),
            ],
            options={
                'verbose_name': 'Training job',
                'verbose_name_plural': 'Training jobs',
                'db_table': 'training_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='training_jo_status_20fc5c_idx'), models.Index(fields=['-created_at'], name='training_jo_created_8d1c09_idx')],
            },
        ),
    ]
