# Generated by Django 6.0 on 2026-01-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_add_training_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('training', 'En Formation'), ('archived', 'Archivé')], db_index=True, default='inactive', max_length=20, verbose_name='status'),
        ),
    ]
